version: '3.8'
services:
db:
image: postgres:15
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: university
volumes:
- pgdata:/var/lib/postgresql/data
ports:
- "5432:5432"


api:
build: ./api
env_file: ./api/.envg
ports:
- "4000:4000"
depends_on:
- db
volumes:
- ./api:/app


volumes:
pgdata: