version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      #  shorter interval for faster local dev startup
      test: ["CMD-SHELL", "pg_isready -U postgres -d university -h localhost"]
      interval: 5s 
      timeout: 3s
      retries: 5

  # 🚀 The Application Service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    # Environment variables for Node.js application to connect to the DB
    environment:
      # DB_HOST 
      DB_HOST: db 
      DB_PORT: 5432
      DB_NAME: university
      DB_USER: postgres
      DB_PASSWORD: postgres
      NODE_ENV: development
    ports:
      - "4000:4000"
    depends_on:
      #  database to be healthy before starting the app/migration
      db:
        condition: service_healthy 
    #  restart always for production, but not strictly needed for local dev
    restart: "on-failure" 

volumes:
  pgdata: